apiVersion: v2
name: platspec-operator
description: Open-source Kubernetes operator implementing the Platform Specification processing layer
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - kubernetes
  - operator
  - platform-specification
  - platformspec
  - kopf
maintainers:
  - name: Josh West
    email: josh@foundation.io
sources:
  - https://gitlab.com/platformspec/platspec-operator
