kubernetes:
  namespace: null

logging:
  level: DEBUG
  format: text

blueprint:
  blueprint_dir: "./blueprints"
  cache_enabled: false
  kcl_timeout: 15

operator:
  reconcile_interval: 60
  max_workers: 3
  finalizer_name: platspec.io/dev-finalizer
  field_manager: platspec-operator

dev_mode: true
debug: true
