apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodes.build.platformspec.io
spec:
  group: build.platformspec.io
  names:
    kind: Node
    listKind: NodeList
    plural: nodes
    singular: node
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Region
          type: string
          jsonPath: .spec.region
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerRefs:
                  type: array
                  items:
                    type: object
                    required: [name]
                    properties:
                      name:
                        type: string
                      kind:
                        type: string
                        default: Provider
                environmentRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                      default: Environment
                region:
                  type: string
                  description: Cloud region where this node type is available.
                networkRefs:
                  type: array
                  items:
                    type: object
                    required: [name]
                    properties:
                      name:
                        type: string
                      kind:
                        type: string
                        default: Network
                config:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  description: Node configuration (size, machineImageRef, etc).
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
